### ISSUE TITLE
delete key ("." or "del") on FX row zero disallows input

### ISSUE THREAD

**Issue by offten** [JoepVanlier/Hackey-Trackey#87]
When entering automation. A zero is continually displayed instead, forcing you to reset automation to display any other value.

Also using SHIFT + BACKSPACE on an FX column causes a crash:

...Roaming\REAPER\Scripts\Tracker tools\Tracker\tracker.lua:7471: attempt to perform arithmetic on a nil value (local 'cpShift')

**Comment by JoepVanlier** [comment]
Hey, thanks for bringing this to my attention!

Regarding behaviour one:
- A zero is continually displayed instead, forcing you to reset automation to display any other value.

Do you mean the top row? If so, that's a limitation of the environment. In REAPER, the automation item has to start with a particular value.

Issue 2 should be fixed in `2.85` though!
