### ISSUE TITLE
Cannot dock Hackey-Trackey in OS X Reaper

### ISSUE THREAD

**Issue by NeuroNoNeuro** [JoepVanlier/Hackey-Trackey#91]
Would love to be able to do this, because having a tracker as part of the main window would make this like a maxxed-out version of Renoise!  Spent an hour looking for solutions all over the 'net.  No luck.  Same would go for the Buzz-machines screen.

**Comment by JoepVanlier** [comment]
Unfortunately, I don't have a Mac to test this on, but if you click with the right mouse button on the title bar of the window, does it not offer the option to dock, like in the screenshot below?
![image](https://user-images.githubusercontent.com/19836026/198902900-8426ce4f-ac71-4264-8df3-7c9c532148a1.png)

**Comment by NeuroNoNeuro** [comment]
> 

Unfortunately, there is no 'window in Docker' option on the Mac, and I've clicked all over the window with a varying combination of both left and right mouse clicks as well as pressing shift/alt/option/ctrl.  No combination seems to work.

**Comment by JoepVanlier** [comment]
I asked around and indeed, on mac, it's up to the script writer to allow the user to toggle the docking state. Thanks for opening the issue on this, since I was really not aware of this.

I've just added a right click menu (right click anywhere in the plugin that's not on the pattern itself) to open a menu that will allow you to dock / un-dock.

**Comment by JoepVanlier** [comment]
Closing this issue now, since all three have the option to dock from the UI now. Once again, thanks for the heads up on this! :)
