### ISSUE TITLE
Sampler channels involved in note transpose

### ISSUE THREAD

**Issue by NeuroNoNeuro** [JoepVanlier/Hackey-Trackey#92]
On the Mac, I can transpose the notes - using the sampler, the transposition also includes the sample location.  Transpose up a note, no more sample playback, because it's on the next sample pad (which had no sample in it).

**Comment by JoepVanlier** [comment]
Ah sorry I only just noticed this issue and from the description it's not entirely clear to me what needs fixing yet.

Are you using the sampler in note toggle mode (where which pad to active is controlled by the note)? Or in regular mode (where there is a dedicated sample column and you can play samples at different pitches)?

And do you mean transposition in the sampler JSFX itself or when transposing in Hackey Trackey itself?

Transposition in Hackey Trackey itself should only apply to whatever is selected in the block. I could add a config option to make HT ignore the sample column when doing transposition if that'd solve the issue.

If possible, a GIF to illustrate what you mean would be very helpful.

**Comment by NeuroNoNeuro** [comment]
> Ah sorry I only just noticed this issue and from the description it's not entirely clear to me what needs fixing yet.
> 
> Are you using the sampler in note toggle mode (where which pad to active is controlled by the note)? Or in regular mode (where there is a dedicated sample column and you can play samples at different pitches)?
> 
> And do you mean transposition in the sampler JSFX itself or when transposing in Hackey Trackey itself?
> 
> Transposition in Hackey Trackey itself should only apply to whatever is selected in the block. I could add a config option to make HT ignore the sample column when doing transposition if that'd solve the issue.
> 
> If possible, a GIF to illustrate what you mean would be very helpful.

Sampler is in Regular Mode, and the transposition was in Hackey Trackey.

This is a weird one - the last time I was using the tracker, I actually had a Ch. 1.  Now I've only got a Ch. 2.  I'm really not too interested in getting this to work any longer, because Renoise really is taking care of the tracker-work for me.  Thanks for getting back to me, though!

**Comment by JoepVanlier** [comment]
It was always emitting to channel 2 and up in multi-channel mode. Since I have to store the note/channel assignment somehow and have to keep track of anything that hasn't been explicitly assigned yet, one channel is lost to "unassigned notes". Channel 1 is used for notes that still need specific channel assignment. There are unfortunately some limitations when you map MIDI to a tracked format and this is one of them. It's described here a bit https://github.com/JoepVanlier/Hackey-Trackey#what-midi-channel-is-used . There was another issue with a report that showing channel 1 was unnecessarily confusing, so I changed the default numbering to start at 2 instead. You can still set a flag in the config to get the old behavior back though.

As for the transpose, maybe you had the entire column (or multiple columns) selected then. It would probably make sense to have a default mode in which the velocity and/or sample number doesn't get transposed with. I'll put it on the backlog.

But yes, fair enough. Renoise is very nice and if you're mostly tracking, then it's likely the best tool for the job. If you ever want to give HT another shot in the future and run into issues, feel free to open a new issue. Closing this one for now then.
